DROP TABLE MEMBER cascade constraint;

CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR2(20) PRIMARY KEY, 
	MEMBER_PASSWORD CHAR(60) NOT NULL,
 	MEMBER_NAME VARCHAR2(100) NOT NULL,
	MEMBER_EMAIL VARCHAR2(100) NOT NULL
);

DROP TABLE AUTHORITIES;

CREATE TABLE AUTHORITIES(
	USERNAME VARCHAR2(100) NOT NULL, 
	ROLE VARCHAR(30) NOT NULL,   
	CONSTRAINT MEMBER_AUTHORITIES_FK FOREIGN KEY(USERNAME) REFERENCES MEMBER(MEMBER_ID),
	CONSTRAINT AUTHORITIES_PK PRIMARY KEY(USERNAME,ROLE)
);







